### ISSUE TITLE
Use exact dependency version for zwave-js in package.json

### ISSUE THREAD

**Issue by Broekman** [zwave-js/zwave-js-server#469]
Hi,

Running zwave-js-server (1.13.0) with zwave-js 8.8.3 (latest) of zwave-js fails on some dependency issues (see below), but works with v8.8.2. In the package dependency ^8.8.2 is specified. For specifically zwave-js, wouldn't it be better to use the exact version that is verified to be working with a specific release of zwave-js-server? I know there is an open PR adding these node commands, however I still think it's good to have zwave-js on a specific version, to prevent such things in the future when zwave-js is updated.

If agreed I can create a PR.

Thank you!

```
TSError: ⨯ Unable to compile TypeScript:
src/lib/node/message_handler.ts:3:3 - error TS2305: Module '"zwave-js"' has no exported member 'LifelineHealthCheckSummary'.

3   LifelineHealthCheckSummary,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib/node/message_handler.ts:4:3 - error TS2305: Module '"zwave-js"' has no exported member 'RouteHealthCheckSummary'.

4   RouteHealthCheckSummary,
    ~~~~~~~~~~~~~~~~~~~~~~~
src/lib/node/message_handler.ts:124:30 - error TS2339: Property 'checkLifelineHealth' does not exist on type 'ZWaveNode'.

124         summary = await node.checkLifelineHealth(
                                 ~~~~~~~~~~~~~~~~~~~
src/lib/node/message_handler.ts:141:30 - error TS2339: Property 'checkRouteHealth' does not exist on type 'ZWaveNode'.

141         summary = await node.checkRouteHealth(
                                 ~~~~~~~~~~~~~~~~

    at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
```

**Comment by MartinHjelmare** [comment]
In practice we often upgrade zwave-js separately of the server in the applications. I don't think we should have a strict coupling.

**Comment by Broekman** [comment]
Hi Martin,

Thanks for your quick response.

I see where you're coming from, but in reality, by releasing e.g. a v1.13.0 with this package dependency, you say it works with >=8.8.2 zwave-js, which it doesn't and it's bound to fail for any update that is made to zwave-js, even more so because it's still actively under development. For anyone installing it without the additional step of manually installing/rolling back to v8.8.2, it fails. I do think strict coupling a gigantic dependency (i.e. the back-bone doing all the work), is a good thing here.

**Comment by raman325** [comment]
Normally the server stays in close lockstep to the driver. We were in a unique position where new commands were introduced that ended up being reverted temporarily. We decided to keep them and to wait for the driver to reintroduced them. Maybe it was a mistake, maybe it was the right thing to do. But I think you are overstating the problem and perhaps missing the above context that led us to where we are.

**Comment by Broekman** [comment]
Hi Raman, no need to explain and albeit unique, it did happen and it can/will happen again.

IMHO, a specific application release should be self sustained. Currently there is no way of easily rolling back or testing specific releases without having to manually look for which dependencies were a part of which release and what works with what. A release should be static and the same everywhere, which it isn't now on many systems as it's dependent on the time you installed it and if it so happened to have updated dependencies in the meantime. I'd rather see all dependencies locked on a specific version per release. Also makes it easier for a maintainer to test/reproduce issues.

Anyhow, as this is is a unique situation, I'm not going to bother you any further as you as maintainers probably have more important things to look at. But proper release management is important, especially with the rapid growth of zwave-js.

**Comment by raman325** [comment]
> it did happen and it can/will happen again.

Will is a strong word but can is fair. This is the first time we've encountered this after 12 months of development, and we are figuring it out as we go. We had an explicit conversation about reverting the commands or waiting for the release that reintroduced them and we chose the latter. Again, it may have been a mistake, it may have been the right thing to do. You're speaking in absolutes which I don't think is fair in this context.
